import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Basic.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Board.geometry}
        material={materials.MatGold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SolidMetal.geometry}
        material={materials.MatGold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SupportCScrew1.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SupportC.geometry}
        material={materials.MatGold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SupportBScrew1.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SupportB.geometry}
        material={materials.MatGold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SupportAScrew4.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SupportAScrew3.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SupportAScrew2.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SupportAScrew1.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SupportA.geometry}
        material={materials.MatGold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseDCover.geometry}
        material={materials.MatGold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseD.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseCScrew1.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseCCover.geometry}
        material={materials.MatGold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseC.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseBScrew3.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseBScrew2.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseBScrew1.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseBCover.geometry}
        material={materials.MatGold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseB.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseAScrew1.geometry}
        material={materials.MatSilver}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseACover.geometry}
        material={materials.MatGold}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BaseA.geometry}
        material={materials.MatSilver}
      />
    </group>
  );
}

useGLTF.preload("/Basic.glb");
